import type { Metadata } from "next";
import { Roboto_Serif } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const roboto = Roboto_Serif({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>
  <title>Hrms Gitlime</title>
      <meta
      name="description"
      content="Gitlime HRMS offers a powerful, user-friendly platform to manage all aspects of human resources, including payroll, employee management, attendance tracking, and more. Simplify your HR processes and enhance productivity with our all-in-one solution."
    />
      <meta
      name="keywords"
      content="HR Management Software, Human Resource Management, HRMS, Payroll Software, Employee Management, Attendance Tracking, Workforce Management, HR Solutions, HR Software, Gitlime HRMS"
    />
      <meta
      property="og:description"
      content="Discover innovative web development services with Gitlime. From website design to ERP development, we provide comprehensive solutions to bring your digital vision to life."
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    <meta name="author" content="Abhishek Singh"/>
    
    <meta name="robots" content="index, follow"/>
    
    <meta property="article:published_time" content="2024-09-03T12:00:00Z"/>
    <meta property="article:modified_time" content="2024-09-03T14:00:00Z"></meta>
    <meta property="og:image" content="/img/seo-images/seo-img-index.png" />
    <meta property="og:url" content=": https://www.hrms.gitlime.com/" />
    <meta property="og:type" content="website" />
    <meta
      name="twitter:title"
      content="Gitlime: Top-Rated Web Development Services &amp; Digital Products"
    />
    <meta
      name="twitter:description"
      content="Discover innovative web development services with Gitlime. From website design to ERP development, we provide comprehensive solutions to bring your digital vision to life."
    />
    <meta name="twitter:image" content="/img/seo-image-index.png" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@Gitlimehq" />
  </head>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
